export const getCardStyles = (c, s, r, t, e) => ({
  card: {
    default: {
      backgroundColor: c.cardSecondary,
      borderRadius: r.md,
      overflow: 'hidden',
    },
    body: {
      padding: s.lg,
    },
  },
  gameCard: {
    container: {
      backgroundColor: c.cardMain,
      borderRadius: r.lg,
      padding: s.md,
      marginBottom: s.xl,
      borderWidth: 1,
      borderColor: c.border,
      overflow: 'hidden',
      shadowColor: c.shadow,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.1,
      shadowRadius: 8,
      elevation: e.medium,
    },
    interactive: {
      // can be used for pressable feedback
    },
    content: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    image: {
      width: 80,
      height: 80,
      borderRadius: r.md,
      marginRight: s.lg,
    },
    info: {
      flex: 1,
      justifyContent: 'center',
    },
    name: {
      fontSize: t.sizes.lg + 2,
      fontFamily: t.families.header,
      color: c.textMain,
      marginBottom: 2,
    },
    ratingRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: 4,
    },
    statsRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: s.lg,
      marginTop: s.sm,
    },
    statItem: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
    },
    statText: {
      fontSize: t.sizes.sm,
      fontFamily: t.families.body,
      color: c.textSecondary,
    },
    expanded: {
      marginTop: s.lg,
      paddingTop: s.lg,
      borderTopWidth: 1,
      borderTopColor: c.divider,
    },
    expandedDataGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: s.md,
      marginBottom: s.md,
    },
    expandedDataItem: {
      borderRadius: r.sm,
      backgroundColor: c.cardSecondary,
      paddingHorizontal: s.md,
      paddingVertical: 4,
      marginBottom: s.xs,
    },
    label: {
      fontSize: t.sizes.xs,
      fontFamily: t.families.subheader,
      color: c.textSecondary,
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    value: {
      fontSize: t.sizes.sm,
      fontFamily: t.families.bodyBold,
      color: c.textMain,
    },
    sectionTitle: {
      fontSize: t.sizes.sm,
      fontFamily: t.families.header,
      color: c.textMain,
      marginBottom: s.xs,
      marginTop: s.sm,
    },
    tagCloud: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: s.xs,
    },
    tag: {
      backgroundColor: c.cardSecondary,
      paddingHorizontal: s.md,
      paddingVertical: 4,
      borderRadius: r.sm,
      borderWidth: 1,
      borderColor: c.divider,
      marginBottom: 2,
    },
    tagText: {
      fontSize: t.sizes.xs,
      fontFamily: t.families.body,
      color: c.textSecondary,
    },
    description: {
      fontSize: t.sizes.sm,
      fontFamily: t.families.body,
      color: c.textSecondary,
      lineHeight: 20,
      marginTop: s.md,
      marginBottom: s.md,
      textAlign: 'left',
    },
  },
  selectedGameCard: {
    width: '100%',
    maxWidth: 320,
    backgroundColor: c.cardSecondary,
    borderRadius: r.lg - 2,
    overflow: 'hidden',
    marginBottom: s['2xl'],
    shadowColor: c.shadow,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: e.high,
  },
  selectedGameContent: {
    flex: 1,
    zIndex: 2,
    paddingHorizontal: s.xl,
    paddingTop: s.xl,
    paddingBottom: s['2xl'],
    alignItems: 'center',
  },
  cardImage: {
    width: '100%',
    height: 180,
    borderRadius: r.md,
    backgroundColor: c.cardMain,
  },
  cardImagePlaceholder: {
    backgroundColor: c.cardMain,
  },
  cardBody: {
    padding: s.lg,
  },
  cardName: {
    fontSize: t.sizes.xl,
    fontFamily: t.families.header,
    color: c.textMain,
  },
  cardDetail: {
    fontSize: t.sizes.md - 1,
    fontFamily: t.families.body,
    color: c.textSecondary,
    marginTop: s.xs,
  },
  noMatchesCard: {
    backgroundColor: c.cardSecondary,
    borderRadius: r.md,
    padding: s.lg,
    marginBottom: s.xl,
    borderLeftWidth: 4,
    borderLeftColor: c.tintMain,
  },
  noMatchesTitle: {
    fontSize: t.sizes.lg,
    fontFamily: t.families.header,
    color: c.textMain,
    marginBottom: s.sm,
  },
  noMatchesBody: {
    fontSize: t.sizes.md - 1,
    fontFamily: t.families.body,
    color: c.textSecondary,
  },
  matchCount: {
    fontSize: t.sizes.md,
    fontFamily: t.families.header,
    color: c.tintMain,
    marginBottom: s.lg,
  },
  ritualCard: {
    backgroundColor: c.cardSecondary,
    borderRadius: r.lg - 2,
    padding: s.lg,
    marginBottom: s.md + 2,
  },
});
